@baseUrl = http://localhost:3001/api/v1/products

@id = 11

### read all products
GET {{baseUrl}}

### read product from ID
GET {{baseUrl}}/{{id}}


### search from query way
GET {{baseUrl}}?search=iphone

### CREATE a new product
POST {{baseUrl}}
Content-Type: application/json

{
  "name": "AirPods 5",
  "price": 4990,
  "quantity": 55
}


### UPDATE a product info data
PUT {{baseUrl}}/{{id}}
Content-Type: application/json

{
  "name": "AirPods 5 ANC",
  "price": 5290,
  "quantity": 60
}


### DELETE a product
DELETE {{baseUrl}}/{{id}}